kind: pipeline
type: docker
name: build

steps:
  - name: hadolint
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint --version
      - hadolint --verbose --failure-threshold warning Dockerfile
      - hadolint --verbose --failure-threshold warning Dockerfile.ci

  - name: gosec
    image: securego/gosec
    commands:
      - gosec --version
      - gosec ./...

  - name: go_test
    image: golang:1.22
    commands:
      - go version
      - go test -v ./...
  
  - name: sqlc
    image: golang:1.22
    commands:
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - sqlc diff
      - sqlc vet
      - sqlc verify

  - name: build
    image: golang:1.22.6-alpine3.20
    commands:
      - apk add --no-cache make=4.4.1-r2
      - make -j "$(nproc)"
    depends_on:
      - sqlc
      - go_test
      - gosec

  - name: kaniko
    image: plugins/kaniko
    settings:
      dockerfile: Dockerfile.ci
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: marcsello/ponyhug2-backend
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}
    when:
      branch:
        - master
    depends_on:
      - hadolint
      - build

  - name: telegram
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_CHAT_ID
    when:
      status: [ failure ]
    depends_on:
      - build
      - kaniko
