// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CardBase struct {
	ID     int16
	Key    *string
	Name   string
	Source *string
	Place  int32
}

type CardCopy struct {
	ID        int32
	PlayerID  int16
	BaseID    int16
	Timestamp pgtype.Timestamp
	WearLevel int16
	Key       string
}

type CardWearImg struct {
	BaseID    int16
	WearLevel int16
	ImageUrl  string
}

type Player struct {
	ID         int16
	Name       string
	Registered pgtype.Timestamp
	IsAdmin    bool
}
