// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CardBase struct {
	ID       int32
	Key      *string
	Name     string
	Story    *string
	Source   *string
	ImageUrl string
	Place    int32
}

type CardCopy struct {
	ID        int32
	PlayerID  int32
	BaseID    int32
	Timestamp pgtype.Timestamp
	WearLevel int16
	Key       string
}

type Player struct {
	ID         int32
	Name       string
	Registered pgtype.Timestamp
	IsAdmin    bool
}
