// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const getCardBase = `-- name: GetCardBase :one
SELECT id, key, name, story, source, image_url, place FROM card_base
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCardBase(ctx context.Context, id int32) (CardBase, error) {
	row := q.db.QueryRow(ctx, getCardBase, id)
	var i CardBase
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Story,
		&i.Source,
		&i.ImageUrl,
		&i.Place,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, name, registered, is_admin FROM player
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlayer(ctx context.Context, id int32) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Registered,
		&i.IsAdmin,
	)
	return i, err
}
